const express = require("express");
const cors = require("cors");
const { response } = require("express");

const app = express();
app.use(cors());
app.use(express.json());
app.get("/ipl", (request, response) => {
  response.send({
    teams: [
      {
        name: "Royal Challengers Bangalore",
        id: "RCB",
        team_image_url:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
      },
      {
        name: "Kolkata Knight Riders",
        id: "KKR",
        team_image_url:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
      },
      {
        name: "Kings XI Punjab",
        id: "KXP",
        team_image_url:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
      },
      {
        name: "Chennai Super Kings",
        id: "CSK",
        team_image_url:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
      },
      {
        name: "Rajasthan Royals",
        id: "RR",
        team_image_url:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
      },
      {
        name: "Mumbai Indians",
        id: "MI",
        team_image_url:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
      },
      {
        name: "Sunrisers Hyderabad",
        id: "SH",
        team_image_url:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
      },
      {
        name: "Delhi Capitals",
        id: "DC",
        team_image_url:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
      },
    ],
  });
});

app.get("/ipl/RCB", (request, response) => {
  response.send({
    team_banner_url:
      "https://assets.ccbp.in/frontend/react-js/kkr-team-img.png",
    latest_match_details: {
      umpires: "CB Gaffaney, VK Sharma",
      result: "Kolkata Knight Riders Won by 7 wickets",
      man_of_the_match: "Shubman Gill",
      id: "1216545",
      date: "2020-09-26",
      venue: "At Sheikh Zayed Stadium, Abu Dhabi",
      competing_team: "Sunrisers Hyderabad",
      competing_team_logo:
        "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
      first_innings: "Sunrisers Hyderabad",
      second_innings: "Kolkata Knight Riders",
      match_status: "Won",
    },
    recent_matches: [
      {
        umpires: "RK Illingworth, K Srinivasan",
        result: "Royal Challengers Bangalore Won by 82 runs",
        man_of_the_match: "AB de Villiers",
        id: "1216540",
        date: "2020-10-12",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Royal Challengers Bangalore",
        second_innings: "Kolkata Knight Riders",
        match_status: "Lost",
      },
      {
        umpires: "C Shamshuddin, RK Illingworth",
        result: "Chennai Super Kings Won by 6 wickets",
        man_of_the_match: "RD Gaikwad",
        id: "1216536",
        date: "2020-10-29",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Chennai Super Kings",
        match_status: "Lost",
      },
      {
        umpires: "Nitin Menon, PR Reiffel",
        result: "Kolkata Knight Riders Won by 60 runs",
        man_of_the_match: "PJ Cummins",
        id: "1216530",
        date: "2020-11-01",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Rajasthan Royals",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, VK Sharma",
        result: "Mumbai Indians Won by 8 wickets",
        man_of_the_match: "Q de Kock",
        id: "1216526",
        date: "2020-10-16",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Mumbai Indians",
        match_status: "Lost",
      },
      {
        umpires: "UV Gandhe, CB Gaffaney",
        result: "Kolkata Knight Riders Won by 2 runs",
        man_of_the_match: "KD Karthik",
        id: "1216523",
        date: "2020-10-10",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Kings XI Punjab",
        match_status: "Won",
      },
      {
        umpires: "KN Ananthapadmanabhan, RK Illingworth",
        result: "Kings XI Punjab Won by 8 wickets",
        man_of_the_match: "CH Gayle",
        id: "1216520",
        date: "2020-10-26",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Kings XI Punjab",
        match_status: "Lost",
      },
      {
        umpires: "VA Kulkarni, RK Illingworth",
        result: "Delhi Capitals Won by 18 runs",
        man_of_the_match: "SS Iyer",
        id: "1216515",
        date: "2020-10-03",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Kolkata Knight Riders",
        match_status: "Lost",
      },
      {
        umpires: "PG Pathak, S Ravi",
        result: "Kolkata Knight Riders Won by NA tie",
        man_of_the_match: "LH Ferguson",
        id: "1216512",
        date: "2020-10-18",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, S Ravi",
        result: "Mumbai Indians Won by 49 runs",
        man_of_the_match: "RG Sharma",
        id: "1216508",
        date: "2020-09-23",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Kolkata Knight Riders",
        match_status: "Lost",
      },
      {
        umpires: "KN Ananthapadmanabhan, C Shamshuddin",
        result: "Kolkata Knight Riders Won by 37 runs",
        man_of_the_match: "Shivam Mavi",
        id: "1216504",
        date: "2020-09-30",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Rajasthan Royals",
        match_status: "Won",
      },
      {
        umpires: "KN Ananthapadmanabhan, RK Illingworth",
        result: "Kolkata Knight Riders Won by 10 runs",
        man_of_the_match: "RA Tripathi",
        id: "1216501",
        date: "2020-10-07",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Chennai Super Kings",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, PG Pathak",
        result: "Kolkata Knight Riders Won by 59 runs",
        man_of_the_match: "CV Varun",
        id: "1216497",
        date: "2020-10-24",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Delhi Capitals",
        match_status: "Won",
      },
      {
        umpires: "VK Sharma, S Ravi",
        result: "Royal Challengers Bangalore Won by 8 wickets",
        man_of_the_match: "Mohammed Siraj",
        id: "1216494",
        date: "2020-10-21",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Royal Challengers Bangalore",
        match_status: "Lost",
      },
    ],
  });
});

app.get("/ipl/KKR", (request, response) => {
  response.send({
    team_banner_url:
      "https://assets.ccbp.in/frontend/react-js/kkr-team-img.png",
    latest_match_details: {
      umpires: "CB Gaffaney, VK Sharma",
      result: "Kolkata Knight Riders Won by 7 wickets",
      man_of_the_match: "Shubman Gill",
      id: "1216545",
      date: "2020-09-26",
      venue: "At Sheikh Zayed Stadium, Abu Dhabi",
      competing_team: "Sunrisers Hyderabad",
      competing_team_logo:
        "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
      first_innings: "Sunrisers Hyderabad",
      second_innings: "Kolkata Knight Riders",
      match_status: "Won",
    },
    recent_matches: [
      {
        umpires: "RK Illingworth, K Srinivasan",
        result: "Royal Challengers Bangalore Won by 82 runs",
        man_of_the_match: "AB de Villiers",
        id: "1216540",
        date: "2020-10-12",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Royal Challengers Bangalore",
        second_innings: "Kolkata Knight Riders",
        match_status: "Lost",
      },
      {
        umpires: "C Shamshuddin, RK Illingworth",
        result: "Chennai Super Kings Won by 6 wickets",
        man_of_the_match: "RD Gaikwad",
        id: "1216536",
        date: "2020-10-29",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Chennai Super Kings",
        match_status: "Lost",
      },
      {
        umpires: "Nitin Menon, PR Reiffel",
        result: "Kolkata Knight Riders Won by 60 runs",
        man_of_the_match: "PJ Cummins",
        id: "1216530",
        date: "2020-11-01",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Rajasthan Royals",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, VK Sharma",
        result: "Mumbai Indians Won by 8 wickets",
        man_of_the_match: "Q de Kock",
        id: "1216526",
        date: "2020-10-16",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Mumbai Indians",
        match_status: "Lost",
      },
      {
        umpires: "UV Gandhe, CB Gaffaney",
        result: "Kolkata Knight Riders Won by 2 runs",
        man_of_the_match: "KD Karthik",
        id: "1216523",
        date: "2020-10-10",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Kings XI Punjab",
        match_status: "Won",
      },
      {
        umpires: "KN Ananthapadmanabhan, RK Illingworth",
        result: "Kings XI Punjab Won by 8 wickets",
        man_of_the_match: "CH Gayle",
        id: "1216520",
        date: "2020-10-26",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Kings XI Punjab",
        match_status: "Lost",
      },
      {
        umpires: "VA Kulkarni, RK Illingworth",
        result: "Delhi Capitals Won by 18 runs",
        man_of_the_match: "SS Iyer",
        id: "1216515",
        date: "2020-10-03",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Kolkata Knight Riders",
        match_status: "Lost",
      },
      {
        umpires: "PG Pathak, S Ravi",
        result: "Kolkata Knight Riders Won by NA tie",
        man_of_the_match: "LH Ferguson",
        id: "1216512",
        date: "2020-10-18",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, S Ravi",
        result: "Mumbai Indians Won by 49 runs",
        man_of_the_match: "RG Sharma",
        id: "1216508",
        date: "2020-09-23",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Kolkata Knight Riders",
        match_status: "Lost",
      },
      {
        umpires: "KN Ananthapadmanabhan, C Shamshuddin",
        result: "Kolkata Knight Riders Won by 37 runs",
        man_of_the_match: "Shivam Mavi",
        id: "1216504",
        date: "2020-09-30",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Rajasthan Royals",
        match_status: "Won",
      },
      {
        umpires: "KN Ananthapadmanabhan, RK Illingworth",
        result: "Kolkata Knight Riders Won by 10 runs",
        man_of_the_match: "RA Tripathi",
        id: "1216501",
        date: "2020-10-07",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Chennai Super Kings",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, PG Pathak",
        result: "Kolkata Knight Riders Won by 59 runs",
        man_of_the_match: "CV Varun",
        id: "1216497",
        date: "2020-10-24",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Delhi Capitals",
        match_status: "Won",
      },
      {
        umpires: "VK Sharma, S Ravi",
        result: "Royal Challengers Bangalore Won by 8 wickets",
        man_of_the_match: "Mohammed Siraj",
        id: "1216494",
        date: "2020-10-21",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Royal Challengers Bangalore",
        match_status: "Lost",
      },
    ],
  });
});

app.get("/ipl/KXP", (request, response) => {
  response.send({
    team_banner_url:
      "https://assets.ccbp.in/frontend/react-js/kxp-team-img.png",
    latest_match_details: {
      umpires: "C Shamshuddin, RK Illingworth",
      result: "Kings XI Punjab Won by 5 wickets",
      man_of_the_match: "S Dhawan",
      id: "1216546",
      date: "2020-10-20",
      venue: "At Dubai International Cricket Stadium, Dubai",
      competing_team: "Delhi Capitals",
      competing_team_logo:
        "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
      first_innings: "Delhi Capitals",
      second_innings: "Kings XI Punjab",
      match_status: "Won",
    },
    recent_matches: [
      {
        umpires: "AK Chaudhary, Nitin Menon",
        result: "Sunrisers Hyderabad Won by 69 runs",
        man_of_the_match: "JM Bairstow",
        id: "1216542",
        date: "2020-10-08",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Sunrisers Hyderabad",
        second_innings: "Kings XI Punjab",
        match_status: "Lost",
      },
      {
        umpires: "CB Gaffaney, S Ravi",
        result: "Rajasthan Royals Won by 7 wickets",
        man_of_the_match: "BA Stokes",
        id: "1216537",
        date: "2020-10-30",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Kings XI Punjab",
        second_innings: "Rajasthan Royals",
        match_status: "Lost",
      },
      {
        umpires: "KN Ananthapadmanabhan, C Shamshuddin",
        result: "Kings XI Punjab Won by 8 wickets",
        man_of_the_match: "KL Rahul",
        id: "1216531",
        date: "2020-10-15",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Royal Challengers Bangalore",
        second_innings: "Kings XI Punjab",
        match_status: "Won",
      },
      {
        umpires: "RK Illingworth, K Srinivasan",
        result: "Rajasthan Royals Won by 4 wickets",
        man_of_the_match: "SV Samson",
        id: "1216527",
        date: "2020-09-27",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Kings XI Punjab",
        second_innings: "Rajasthan Royals",
        match_status: "Lost",
      },
      {
        umpires: "UV Gandhe, CB Gaffaney",
        result: "Kolkata Knight Riders Won by 2 runs",
        man_of_the_match: "KD Karthik",
        id: "1216523",
        date: "2020-10-10",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Kolkata Knight Riders",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Kings XI Punjab",
        match_status: "Lost",
      },
      {
        umpires: "KN Ananthapadmanabhan, RK Illingworth",
        result: "Kings XI Punjab Won by 8 wickets",
        man_of_the_match: "CH Gayle",
        id: "1216520",
        date: "2020-10-26",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Kolkata Knight Riders",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Kings XI Punjab",
        match_status: "Won",
      },
      {
        umpires: "Nitin Menon, PR Reiffel",
        result: "Kings XI Punjab Won by NA tie",
        man_of_the_match: "KL Rahul",
        id: "1216517",
        date: "2020-10-18",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Kings XI Punjab",
        match_status: "Won",
      },
      {
        umpires: "AY Dandekar, Nitin Menon",
        result: "Chennai Super Kings Won by 10 wickets",
        man_of_the_match: "SR Watson",
        id: "1216513",
        date: "2020-10-04",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Kings XI Punjab",
        second_innings: "Chennai Super Kings",
        match_status: "Lost",
      },
      {
        umpires: "AK Chaudhary, PR Reiffel",
        result: "Kings XI Punjab Won by 97 runs",
        man_of_the_match: "KL Rahul",
        id: "1216510",
        date: "2020-09-24",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Kings XI Punjab",
        second_innings: "Royal Challengers Bangalore",
        match_status: "Won",
      },
      {
        umpires: "PG Pathak, VK Sharma",
        result: "Chennai Super Kings Won by 9 wickets",
        man_of_the_match: "RD Gaikwad",
        id: "1216506",
        date: "2020-11-01",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Kings XI Punjab",
        second_innings: "Chennai Super Kings",
        match_status: "Lost",
      },
      {
        umpires: "VK Sharma, S Ravi",
        result: "Mumbai Indians Won by 48 runs",
        man_of_the_match: "KA Pollard",
        id: "1216503",
        date: "2020-10-01",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Kings XI Punjab",
        match_status: "Lost",
      },
      {
        umpires: "AY Dandekar, PR Reiffel",
        result: "Kings XI Punjab Won by 12 runs",
        man_of_the_match: "CJ Jordan",
        id: "1216498",
        date: "2020-10-24",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Kings XI Punjab",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Won",
      },
      {
        umpires: "AK Chaudhary, Nitin Menon",
        result: "Delhi Capitals Won by NA tie",
        man_of_the_match: "MP Stoinis",
        id: "1216493",
        date: "2020-09-20",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Kings XI Punjab",
        match_status: "Lost",
      },
    ],
  });
});

app.get("/ipl/CSK", (request, response) => {
  response.send({
    team_banner_url:
      "https://assets.ccbp.in/frontend/react-js/csk-team-img.png",
    latest_match_details: {
      umpires: "C Shamshuddin, RK Illingworth",
      result: "Chennai Super Kings Won by 8 wickets",
      man_of_the_match: "RD Gaikwad",
      id: "1216544",
      date: "2020-10-25",
      venue: "At Dubai International Cricket Stadium, Dubai",
      competing_team: "Royal Challengers Bangalore",
      competing_team_logo:
        "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
      first_innings: "Royal Challengers Bangalore",
      second_innings: "Chennai Super Kings",
      match_status: "Won",
    },
    recent_matches: [
      {
        umpires: "KN Ananthapadmanabhan, RK Illingworth",
        result: "Delhi Capitals Won by 44 runs",
        man_of_the_match: "PP Shaw",
        id: "1216539",
        date: "2020-09-25",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Chennai Super Kings",
        match_status: "Lost",
      },
      {
        umpires: "C Shamshuddin, RK Illingworth",
        result: "Chennai Super Kings Won by 6 wickets",
        man_of_the_match: "RD Gaikwad",
        id: "1216536",
        date: "2020-10-29",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Kolkata Knight Riders",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Chennai Super Kings",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, VK Sharma",
        result: "Rajasthan Royals Won by 7 wickets",
        man_of_the_match: "JC Buttler",
        id: "1216533",
        date: "2020-10-19",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Chennai Super Kings",
        second_innings: "Rajasthan Royals",
        match_status: "Lost",
      },
      {
        umpires: "AK Chaudhary, PR Reiffel",
        result: "Chennai Super Kings Won by 20 runs",
        man_of_the_match: "RA Jadeja",
        id: "1216528",
        date: "2020-10-13",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Chennai Super Kings",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Won",
      },
      {
        umpires: "AK Chaudhary, PR Reiffel",
        result: "Royal Challengers Bangalore Won by 37 runs",
        man_of_the_match: "V Kohli",
        id: "1216525",
        date: "2020-10-10",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Royal Challengers Bangalore",
        second_innings: "Chennai Super Kings",
        match_status: "Lost",
      },
      {
        umpires: "C Shamshuddin, VA Kulkarni",
        result: "Mumbai Indians Won by 10 wickets",
        man_of_the_match: "TA Boult",
        id: "1216521",
        date: "2020-10-23",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Chennai Super Kings",
        second_innings: "Mumbai Indians",
        match_status: "Lost",
      },
      {
        umpires: "AK Chaudhary, PR Reiffel",
        result: "Sunrisers Hyderabad Won by 7 runs",
        man_of_the_match: "PK Garg",
        id: "1216516",
        date: "2020-10-02",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Sunrisers Hyderabad",
        second_innings: "Chennai Super Kings",
        match_status: "Lost",
      },
      {
        umpires: "AY Dandekar, Nitin Menon",
        result: "Chennai Super Kings Won by 10 wickets",
        man_of_the_match: "SR Watson",
        id: "1216513",
        date: "2020-10-04",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Kings XI Punjab",
        second_innings: "Chennai Super Kings",
        match_status: "Won",
      },
      {
        umpires: "KN Ananthapadmanabhan, RK Illingworth",
        result: "Delhi Capitals Won by 5 wickets",
        man_of_the_match: "S Dhawan",
        id: "1216509",
        date: "2020-10-17",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Chennai Super Kings",
        second_innings: "Delhi Capitals",
        match_status: "Lost",
      },
      {
        umpires: "PG Pathak, VK Sharma",
        result: "Chennai Super Kings Won by 9 wickets",
        man_of_the_match: "RD Gaikwad",
        id: "1216506",
        date: "2020-11-01",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Kings XI Punjab",
        second_innings: "Chennai Super Kings",
        match_status: "Won",
      },
      {
        umpires: "KN Ananthapadmanabhan, RK Illingworth",
        result: "Kolkata Knight Riders Won by 10 runs",
        man_of_the_match: "RA Tripathi",
        id: "1216501",
        date: "2020-10-07",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Kolkata Knight Riders",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Chennai Super Kings",
        match_status: "Lost",
      },
      {
        umpires: "C Shamshuddin, VA Kulkarni",
        result: "Rajasthan Royals Won by 16 runs",
        man_of_the_match: "SV Samson",
        id: "1216496",
        date: "2020-09-22",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Rajasthan Royals",
        second_innings: "Chennai Super Kings",
        match_status: "Lost",
      },
      {
        umpires: "CB Gaffaney, VK Sharma",
        result: "Chennai Super Kings Won by 5 wickets",
        man_of_the_match: "AT Rayudu",
        id: "1216492",
        date: "2020-09-19",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Chennai Super Kings",
        match_status: "Won",
      },
    ],
  });
});

app.get("/ipl/RR", (request, response) => {
  response.send({
    team_banner_url: "https://assets.ccbp.in/frontend/react-js/rr-team-img.png",
    latest_match_details: {
      umpires: "AK Chaudhary, Nitin Menon",
      result: "Delhi Capitals Won by 13 runs",
      man_of_the_match: "A Nortje",
      id: "1216543",
      date: "2020-10-14",
      venue: "At Dubai International Cricket Stadium, Dubai",
      competing_team: "Delhi Capitals",
      competing_team_logo:
        "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
      first_innings: "Delhi Capitals",
      second_innings: "Rajasthan Royals",
      match_status: "Lost",
    },
    recent_matches: [
      {
        umpires: "UV Gandhe, VK Sharma",
        result: "Rajasthan Royals Won by 8 wickets",
        man_of_the_match: "BA Stokes",
        id: "1216541",
        date: "2020-10-25",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Rajasthan Royals",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, S Ravi",
        result: "Rajasthan Royals Won by 7 wickets",
        man_of_the_match: "BA Stokes",
        id: "1216537",
        date: "2020-10-30",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Kings XI Punjab",
        second_innings: "Rajasthan Royals",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, VK Sharma",
        result: "Rajasthan Royals Won by 7 wickets",
        man_of_the_match: "JC Buttler",
        id: "1216533",
        date: "2020-10-19",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Chennai Super Kings",
        second_innings: "Rajasthan Royals",
        match_status: "Won",
      },
      {
        umpires: "Nitin Menon, PR Reiffel",
        result: "Kolkata Knight Riders Won by 60 runs",
        man_of_the_match: "PJ Cummins",
        id: "1216530",
        date: "2020-11-01",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Kolkata Knight Riders",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Rajasthan Royals",
        match_status: "Lost",
      },
      {
        umpires: "RK Illingworth, K Srinivasan",
        result: "Rajasthan Royals Won by 4 wickets",
        man_of_the_match: "SV Samson",
        id: "1216527",
        date: "2020-09-27",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Kings XI Punjab",
        second_innings: "Rajasthan Royals",
        match_status: "Won",
      },
      {
        umpires: "AK Chaudhary, Nitin Menon",
        result: "Royal Challengers Bangalore Won by 7 wickets",
        man_of_the_match: "AB de Villiers",
        id: "1216522",
        date: "2020-10-17",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Rajasthan Royals",
        second_innings: "Royal Challengers Bangalore",
        match_status: "Lost",
      },
      {
        umpires: "Nitin Menon, PR Reiffel",
        result: "Sunrisers Hyderabad Won by 8 wickets",
        man_of_the_match: "MK Pandey",
        id: "1216518",
        date: "2020-10-22",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Rajasthan Royals",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Lost",
      },
      {
        umpires: "CB Gaffaney, S Ravi",
        result: "Royal Challengers Bangalore Won by 8 wickets",
        man_of_the_match: "YS Chahal",
        id: "1216514",
        date: "2020-10-03",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Rajasthan Royals",
        second_innings: "Royal Challengers Bangalore",
        match_status: "Lost",
      },
      {
        umpires: "VK Sharma, S Ravi",
        result: "Mumbai Indians Won by 57 runs",
        man_of_the_match: "SA Yadav",
        id: "1216511",
        date: "2020-10-06",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Rajasthan Royals",
        match_status: "Lost",
      },
      {
        umpires: "YC Barde, PR Reiffel",
        result: "Rajasthan Royals Won by 5 wickets",
        man_of_the_match: "R Tewatia",
        id: "1216507",
        date: "2020-10-11",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Sunrisers Hyderabad",
        second_innings: "Rajasthan Royals",
        match_status: "Won",
      },
      {
        umpires: "KN Ananthapadmanabhan, C Shamshuddin",
        result: "Kolkata Knight Riders Won by 37 runs",
        man_of_the_match: "Shivam Mavi",
        id: "1216504",
        date: "2020-09-30",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Kolkata Knight Riders",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Rajasthan Royals",
        match_status: "Lost",
      },
      {
        umpires: "KN Ananthapadmanabhan, C Shamshuddin",
        result: "Delhi Capitals Won by 46 runs",
        man_of_the_match: "R Ashwin",
        id: "1216500",
        date: "2020-10-09",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Rajasthan Royals",
        match_status: "Lost",
      },
      {
        umpires: "C Shamshuddin, VA Kulkarni",
        result: "Rajasthan Royals Won by 16 runs",
        man_of_the_match: "SV Samson",
        id: "1216496",
        date: "2020-09-22",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Rajasthan Royals",
        second_innings: "Chennai Super Kings",
        match_status: "Won",
      },
    ],
  });
});

app.get("/ipl/MI", (request, response) => {
  response.send({
    team_banner_url: "https://assets.ccbp.in/frontend/react-js/mi-team-img.png",
    latest_match_details: {
      umpires: "CB Gaffaney, Nitin Menon",
      result: "Mumbai Indians Won by 5 wickets",
      man_of_the_match: "TA Boult",
      id: "1237181",
      date: "2020-11-10",
      venue: "At Dubai International Cricket Stadium, Dubai",
      competing_team: "Delhi Capitals",
      competing_team_logo:
        "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
      first_innings: "Delhi Capitals",
      second_innings: "Mumbai Indians",
      match_status: "Won",
    },
    recent_matches: [
      {
        umpires: "CB Gaffaney, Nitin Menon",
        result: "Mumbai Indians Won by 57 runs",
        man_of_the_match: "JJ Bumrah",
        id: "1237177",
        date: "2020-11-05",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Delhi Capitals",
        match_status: "Won",
      },
      {
        umpires: "Nitin Menon, PR Reiffel",
        result: "Royal Challengers Bangalore Won by NA tie",
        man_of_the_match: "AB de Villiers",
        id: "1216547",
        date: "2020-09-28",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Royal Challengers Bangalore",
        second_innings: "Mumbai Indians",
        match_status: "Lost",
      },
      {
        umpires: "UV Gandhe, VK Sharma",
        result: "Rajasthan Royals Won by 8 wickets",
        man_of_the_match: "BA Stokes",
        id: "1216541",
        date: "2020-10-25",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Rajasthan Royals",
        match_status: "Lost",
      },
      {
        umpires: "KN Ananthapadmanabhan, RK Illingworth",
        result: "Mumbai Indians Won by 34 runs",
        man_of_the_match: "TA Boult",
        id: "1216538",
        date: "2020-10-04",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Won",
      },
      {
        umpires: "YC Barde, PR Reiffel",
        result: "Mumbai Indians Won by 9 wickets",
        man_of_the_match: "Ishan Kishan",
        id: "1216535",
        date: "2020-10-31",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Mumbai Indians",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, S Ravi",
        result: "Mumbai Indians Won by 5 wickets",
        man_of_the_match: "Q de Kock",
        id: "1216529",
        date: "2020-10-11",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Mumbai Indians",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, VK Sharma",
        result: "Mumbai Indians Won by 8 wickets",
        man_of_the_match: "Q de Kock",
        id: "1216526",
        date: "2020-10-16",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Kolkata Knight Riders",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Mumbai Indians",
        match_status: "Won",
      },
      {
        umpires: "C Shamshuddin, VA Kulkarni",
        result: "Mumbai Indians Won by 10 wickets",
        man_of_the_match: "TA Boult",
        id: "1216521",
        date: "2020-10-23",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Chennai Super Kings",
        second_innings: "Mumbai Indians",
        match_status: "Won",
      },
      {
        umpires: "Nitin Menon, PR Reiffel",
        result: "Kings XI Punjab Won by NA tie",
        man_of_the_match: "KL Rahul",
        id: "1216517",
        date: "2020-10-18",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Kings XI Punjab",
        match_status: "Lost",
      },
      {
        umpires: "VK Sharma, S Ravi",
        result: "Mumbai Indians Won by 57 runs",
        man_of_the_match: "SA Yadav",
        id: "1216511",
        date: "2020-10-06",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Rajasthan Royals",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, S Ravi",
        result: "Mumbai Indians Won by 49 runs",
        man_of_the_match: "RG Sharma",
        id: "1216508",
        date: "2020-09-23",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Kolkata Knight Riders",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Kolkata Knight Riders",
        match_status: "Won",
      },
      {
        umpires: "VK Sharma, S Ravi",
        result: "Mumbai Indians Won by 48 runs",
        man_of_the_match: "KA Pollard",
        id: "1216503",
        date: "2020-10-01",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Kings XI Punjab",
        match_status: "Won",
      },
      {
        umpires: "UV Gandhe, CB Gaffaney",
        result: "Mumbai Indians Won by 5 wickets",
        man_of_the_match: "SA Yadav",
        id: "1216499",
        date: "2020-10-28",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Royal Challengers Bangalore",
        second_innings: "Mumbai Indians",
        match_status: "Won",
      },
      {
        umpires: "C Shamshuddin, RK Illingworth",
        result: "Sunrisers Hyderabad Won by 10 wickets",
        man_of_the_match: "S Nadeem",
        id: "1216495",
        date: "2020-11-03",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Lost",
      },
      {
        umpires: "CB Gaffaney, VK Sharma",
        result: "Chennai Super Kings Won by 5 wickets",
        man_of_the_match: "AT Rayudu",
        id: "1216492",
        date: "2020-09-19",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Chennai Super Kings",
        match_status: "Lost",
      },
    ],
  });
});

app.get("/ipl/SH", (request, response) => {
  response.send({
    team_banner_url:
      "https://assets.ccbp.in/frontend/react-js/srh-team-img.png",
    latest_match_details: {
      umpires: "PR Reiffel, S Ravi",
      result: "Delhi Capitals Won by 17 runs",
      man_of_the_match: "MP Stoinis",
      id: "1237180",
      date: "2020-11-08",
      venue: "At Sheikh Zayed Stadium, Abu Dhabi",
      competing_team: "Delhi Capitals",
      competing_team_logo:
        "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
      first_innings: "Delhi Capitals",
      second_innings: "Sunrisers Hyderabad",
      match_status: "Lost",
    },
    recent_matches: [
      {
        umpires: "PR Reiffel, S Ravi",
        result: "Sunrisers Hyderabad Won by 6 wickets",
        man_of_the_match: "KS Williamson",
        id: "1237178",
        date: "2020-11-06",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Royal Challengers Bangalore",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, VK Sharma",
        result: "Kolkata Knight Riders Won by 7 wickets",
        man_of_the_match: "Shubman Gill",
        id: "1216545",
        date: "2020-09-26",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Kolkata Knight Riders",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
        first_innings: "Sunrisers Hyderabad",
        second_innings: "Kolkata Knight Riders",
        match_status: "Lost",
      },
      {
        umpires: "AK Chaudhary, Nitin Menon",
        result: "Sunrisers Hyderabad Won by 69 runs",
        man_of_the_match: "JM Bairstow",
        id: "1216542",
        date: "2020-10-08",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Sunrisers Hyderabad",
        second_innings: "Kings XI Punjab",
        match_status: "Won",
      },
      {
        umpires: "KN Ananthapadmanabhan, RK Illingworth",
        result: "Mumbai Indians Won by 34 runs",
        man_of_the_match: "TA Boult",
        id: "1216538",
        date: "2020-10-04",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Lost",
      },
      {
        umpires: "AY Dandekar, Nitin Menon",
        result: "Royal Challengers Bangalore Won by 10 runs",
        man_of_the_match: "YS Chahal",
        id: "1216534",
        date: "2020-09-21",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Royal Challengers Bangalore",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Lost",
      },
      {
        umpires: "VK Sharma, S Ravi",
        result: "Sunrisers Hyderabad Won by 15 runs",
        man_of_the_match: "Rashid Khan",
        id: "1216532",
        date: "2020-09-29",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Sunrisers Hyderabad",
        second_innings: "Delhi Capitals",
        match_status: "Won",
      },
      {
        umpires: "AK Chaudhary, PR Reiffel",
        result: "Chennai Super Kings Won by 20 runs",
        man_of_the_match: "RA Jadeja",
        id: "1216528",
        date: "2020-10-13",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Chennai Super Kings",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Lost",
      },
      {
        umpires: "AK Chaudhary, Nitin Menon",
        result: "Sunrisers Hyderabad Won by 88 runs",
        man_of_the_match: "WP Saha",
        id: "1216524",
        date: "2020-10-27",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Delhi Capitals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/dc-logo-img.png",
        first_innings: "Sunrisers Hyderabad",
        second_innings: "Delhi Capitals",
        match_status: "Won",
      },
      {
        umpires: "Nitin Menon, PR Reiffel",
        result: "Sunrisers Hyderabad Won by 8 wickets",
        man_of_the_match: "MK Pandey",
        id: "1216518",
        date: "2020-10-22",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Rajasthan Royals",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Won",
      },
      {
        umpires: "AK Chaudhary, PR Reiffel",
        result: "Sunrisers Hyderabad Won by 7 runs",
        man_of_the_match: "PK Garg",
        id: "1216516",
        date: "2020-10-02",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Sunrisers Hyderabad",
        second_innings: "Chennai Super Kings",
        match_status: "Won",
      },
      {
        umpires: "PG Pathak, S Ravi",
        result: "Kolkata Knight Riders Won by NA tie",
        man_of_the_match: "LH Ferguson",
        id: "1216512",
        date: "2020-10-18",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Kolkata Knight Riders",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Lost",
      },
      {
        umpires: "YC Barde, PR Reiffel",
        result: "Rajasthan Royals Won by 5 wickets",
        man_of_the_match: "R Tewatia",
        id: "1216507",
        date: "2020-10-11",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Sunrisers Hyderabad",
        second_innings: "Rajasthan Royals",
        match_status: "Lost",
      },
      {
        umpires: "KN Ananthapadmanabhan, K Srinivasan",
        result: "Sunrisers Hyderabad Won by 5 wickets",
        man_of_the_match: "Sandeep Sharma",
        id: "1216502",
        date: "2020-10-31",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Royal Challengers Bangalore",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Won",
      },
      {
        umpires: "AY Dandekar, PR Reiffel",
        result: "Kings XI Punjab Won by 12 runs",
        man_of_the_match: "CJ Jordan",
        id: "1216498",
        date: "2020-10-24",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Kings XI Punjab",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Lost",
      },
      {
        umpires: "C Shamshuddin, RK Illingworth",
        result: "Sunrisers Hyderabad Won by 10 wickets",
        man_of_the_match: "S Nadeem",
        id: "1216495",
        date: "2020-11-03",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Won",
      },
    ],
  });
});

app.get("/ipl/DC", (request, response) => {
  response.send({
    team_banner_url: "https://assets.ccbp.in/frontend/react-js/dc-team-img.png",
    latest_match_details: {
      umpires: "CB Gaffaney, Nitin Menon",
      result: "Mumbai Indians Won by 5 wickets",
      man_of_the_match: "TA Boult",
      id: "1237181",
      date: "2020-11-10",
      venue: "At Dubai International Cricket Stadium, Dubai",
      competing_team: "Mumbai Indians",
      competing_team_logo:
        "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
      first_innings: "Delhi Capitals",
      second_innings: "Mumbai Indians",
      match_status: "Lost",
    },
    recent_matches: [
      {
        umpires: "PR Reiffel, S Ravi",
        result: "Delhi Capitals Won by 17 runs",
        man_of_the_match: "MP Stoinis",
        id: "1237180",
        date: "2020-11-08",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Sunrisers Hyderabad",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, Nitin Menon",
        result: "Mumbai Indians Won by 57 runs",
        man_of_the_match: "JJ Bumrah",
        id: "1237177",
        date: "2020-11-05",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Mumbai Indians",
        second_innings: "Delhi Capitals",
        match_status: "Lost",
      },
      {
        umpires: "C Shamshuddin, RK Illingworth",
        result: "Kings XI Punjab Won by 5 wickets",
        man_of_the_match: "S Dhawan",
        id: "1216546",
        date: "2020-10-20",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Kings XI Punjab",
        match_status: "Lost",
      },
      {
        umpires: "AK Chaudhary, Nitin Menon",
        result: "Delhi Capitals Won by 13 runs",
        man_of_the_match: "A Nortje",
        id: "1216543",
        date: "2020-10-14",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Rajasthan Royals",
        match_status: "Won",
      },
      {
        umpires: "KN Ananthapadmanabhan, RK Illingworth",
        result: "Delhi Capitals Won by 44 runs",
        man_of_the_match: "PP Shaw",
        id: "1216539",
        date: "2020-09-25",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Chennai Super Kings",
        match_status: "Won",
      },
      {
        umpires: "YC Barde, PR Reiffel",
        result: "Mumbai Indians Won by 9 wickets",
        man_of_the_match: "Ishan Kishan",
        id: "1216535",
        date: "2020-10-31",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Mumbai Indians",
        match_status: "Lost",
      },
      {
        umpires: "VK Sharma, S Ravi",
        result: "Sunrisers Hyderabad Won by 15 runs",
        man_of_the_match: "Rashid Khan",
        id: "1216532",
        date: "2020-09-29",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Sunrisers Hyderabad",
        second_innings: "Delhi Capitals",
        match_status: "Lost",
      },
      {
        umpires: "CB Gaffaney, S Ravi",
        result: "Mumbai Indians Won by 5 wickets",
        man_of_the_match: "Q de Kock",
        id: "1216529",
        date: "2020-10-11",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Mumbai Indians",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/mi-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Mumbai Indians",
        match_status: "Lost",
      },
      {
        umpires: "AK Chaudhary, Nitin Menon",
        result: "Sunrisers Hyderabad Won by 88 runs",
        man_of_the_match: "WP Saha",
        id: "1216524",
        date: "2020-10-27",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Sunrisers Hyderabad",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/srh-logo-img.png",
        first_innings: "Sunrisers Hyderabad",
        second_innings: "Delhi Capitals",
        match_status: "Lost",
      },
      {
        umpires: "Nitin Menon, YC Barde",
        result: "Delhi Capitals Won by 59 runs",
        man_of_the_match: "AR Patel",
        id: "1216519",
        date: "2020-10-05",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Royal Challengers Bangalore",
        match_status: "Won",
      },
      {
        umpires: "VA Kulkarni, RK Illingworth",
        result: "Delhi Capitals Won by 18 runs",
        man_of_the_match: "SS Iyer",
        id: "1216515",
        date: "2020-10-03",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Kolkata Knight Riders",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Kolkata Knight Riders",
        match_status: "Won",
      },
      {
        umpires: "KN Ananthapadmanabhan, RK Illingworth",
        result: "Delhi Capitals Won by 5 wickets",
        man_of_the_match: "S Dhawan",
        id: "1216509",
        date: "2020-10-17",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Chennai Super Kings",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/csk-logo-img.png",
        first_innings: "Chennai Super Kings",
        second_innings: "Delhi Capitals",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, S Ravi",
        result: "Delhi Capitals Won by 6 wickets",
        man_of_the_match: "A Nortje",
        id: "1216505",
        date: "2020-11-02",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Royal Challengers Bangalore",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rcb-logo-img.png",
        first_innings: "Royal Challengers Bangalore",
        second_innings: "Delhi Capitals",
        match_status: "Won",
      },
      {
        umpires: "KN Ananthapadmanabhan, C Shamshuddin",
        result: "Delhi Capitals Won by 46 runs",
        man_of_the_match: "R Ashwin",
        id: "1216500",
        date: "2020-10-09",
        venue: "At Sharjah Cricket Stadium, Sharjah",
        competing_team: "Rajasthan Royals",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/rr-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Rajasthan Royals",
        match_status: "Won",
      },
      {
        umpires: "CB Gaffaney, PG Pathak",
        result: "Kolkata Knight Riders Won by 59 runs",
        man_of_the_match: "CV Varun",
        id: "1216497",
        date: "2020-10-24",
        venue: "At Sheikh Zayed Stadium, Abu Dhabi",
        competing_team: "Kolkata Knight Riders",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kkr-logo-img.png",
        first_innings: "Kolkata Knight Riders",
        second_innings: "Delhi Capitals",
        match_status: "Lost",
      },
      {
        umpires: "AK Chaudhary, Nitin Menon",
        result: "Delhi Capitals Won by NA tie",
        man_of_the_match: "MP Stoinis",
        id: "1216493",
        date: "2020-09-20",
        venue: "At Dubai International Cricket Stadium, Dubai",
        competing_team: "Kings XI Punjab",
        competing_team_logo:
          "https://assets.ccbp.in/frontend/react-js/kxp-logo-img.png",
        first_innings: "Delhi Capitals",
        second_innings: "Kings XI Punjab",
        match_status: "Won",
      },
    ],
  });
});

const port = process.env.PORT || 4000;

app.listen(port, () => {
  console.log("Sever running at port 4000");
});
